/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "sjcxixgtxkdoxjimiqkx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqY3hpeGd0eGtkb3hqaW1pcWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwMTA2ODUsImV4cCI6MjA3NzU4NjY4NX0.ow64f03DrabaK-xX6x2aFPyc_FEi9swnUPIXFQhQI-Q"